name: AlanaDawes
favicon: null
layout_spectrum: 0.91468
typography_spectrum: 0.80387
title: Golden Banana Music Group - Alana Dawes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9d9d9'
    - '#030303'
    - '#252525'
    - '#484848'
    - '#979797'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.47267643362283707
  rhythmicContrast: 0.25
purpose: []
